connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Depot
  password: 

development:
  <<: *connection
  database: dbname_development

test:
  <<: *connection
  database: dbname_test

production:
  <<: *connection
  database: dbname_production